### PR TITLE
Fixup test_term static type checking.

### PR DESCRIPTION
**Pull request by tttc3**
- set reportUnnecessaryTypeIgnoreComment=true, as required by the static type "tests" in `test_term`;

- remove now redundant, commented out, beatype based tests in `test_term`;

- remove all unnecessary type ignore comments from across the codebase.

### CODE REVIEW

**Comment by tttc3** [comment]
The pre-commit complaints are from bumping the pyright version to `1.1.351`. I've had a quick look in `eqx.Enumeration` to see if this can be handled upstream, but I've drawn a blank; any thoughts?

**Comment by patrick-kidger** [comment]
Looks like pyright getting stricter. I've fixed this upsteam on the Equinox dev branch. I'm aiming to do a new release of that fairly shortly, and then we can re-run things here.

**Comment by tttc3** [comment]
I've removed the pyright bump as this wasn't really related to the purpose of this pull.

**Comment by patrick-kidger** [comment]
LGTM! I finally did the new release of Equinox so I'm happy to have this merged.
Thank you for the contribution :D

**Pull request merged**
