### PR TITLE
Enable implicit solvers for complex inputs

### PR DESCRIPTION
**Pull request by Randl**
Related to https://github.com/patrick-kidger/diffrax/issues/388

### CODE REVIEW

**Comment by Randl** [comment]
Ok we need a new release of optimistix (specifically https://github.com/patrick-kidger/optimistix/pull/53) for that one

**Comment by patrick-kidger** [comment]
Ah, I'd been wanting to do a new Optimistix release anyway, so that sounds good to me.

Just to double check before I do: so far as you know, is Optimistix completely ready on the complex-support front? If so then I'll advertise this in the release notes for it.

**Comment by Randl** [comment]
I've added some complex-related tests in the PR and it passed and I didn't encounter any issues when I played with it. I didn't take a look at minimization (complex->real functions) though. Maybe advertise it as "experimental support", and I'll be happy to help with bug fixing if there will be any.

**Comment by Randl** [comment]
@patrick-kidger good to go?

**Pull request merged**
